"""add relation of user like travel and follow relation

Revision ID: 0b91062aac66
Revises: e3cd5d8d72fa
Create Date: 2017-05-25 21:19:19.022334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b91062aac66'
down_revision = 'e3cd5d8d72fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('like',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('follow')
    # ### end Alembic commands ###
