"""user table add register time,travel table add publish time

Revision ID: e3cd5d8d72fa
Revises: 
Create Date: 2017-05-25 19:58:06.488007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cd5d8d72fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel', sa.Column('publish_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('register_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'register_time')
    op.drop_column('travel', 'publish_time')
    # ### end Alembic commands ###
